"""
RMSNorm — auto-tuned build, generated by the VTEC agent on this GPU.

A fused kernel (read x once, write y once) whose launch shape and load path
were picked by timing variants on the machine that submitted it:
  THREADS  = {{THREADS}}   threads per row (each handles {{PER_THREAD}} float4s)
  LOAD     = {{LOAD}}      plain loads or __ldg (read-only cache)
Same math and output as the baseline; VTEC_SEED picks the input and the result
goes to VTEC_OUT for the verifier's harness to compare.
"""
import os
import cupy as cp
import numpy as np

ROWS, COLS, ITERS, EPS = 8192, 4096, 1000, 1e-6
THREADS = {{THREADS}}

KERNEL = r"""
#define T {{THREADS}}
#define K {{PER_THREAD}}
#define LOAD(p) {{LOAD_EXPR}}
extern "C" __global__ void rmsnorm(const float4* __restrict__ x, const float4* __restrict__ w,
                                   float4* __restrict__ y, int cols4, float eps) {
    const float4* row = x + (size_t)blockIdx.x * cols4;
    float4* out = y + (size_t)blockIdx.x * cols4;
    float4 v[K];
    float sum = 0.f;
    #pragma unroll
    for (int k = 0; k < K; k++) {
        v[k] = LOAD(row + threadIdx.x + k * T);
        sum += v[k].x * v[k].x + v[k].y * v[k].y + v[k].z * v[k].z + v[k].w * v[k].w;
    }
    for (int o = 16; o > 0; o >>= 1) sum += __shfl_xor_sync(0xffffffff, sum, o);
    __shared__ float warps[T / 32];
    if ((threadIdx.x & 31) == 0) warps[threadIdx.x >> 5] = sum;
    __syncthreads();
    if (threadIdx.x < 32) {
        float t = threadIdx.x < T / 32 ? warps[threadIdx.x] : 0.f;
        for (int o = 16; o > 0; o >>= 1) t += __shfl_xor_sync(0xffffffff, t, o);
        if (threadIdx.x == 0) warps[0] = t;
    }
    __syncthreads();
    float scale = rsqrtf(warps[0] / (cols4 * 4) + eps);
    #pragma unroll
    for (int k = 0; k < K; k++) {
        int i = threadIdx.x + k * T;
        float4 g = LOAD(w + i);
        out[i] = make_float4(v[k].x * scale * g.x, v[k].y * scale * g.y, v[k].z * scale * g.z, v[k].w * scale * g.w);
    }
}
"""

def main():
    seed = int(os.environ.get("VTEC_SEED", "0"))
    rng = cp.random.default_rng(seed)
    x = rng.standard_normal((ROWS, COLS), dtype=cp.float32)
    w = rng.standard_normal(COLS, dtype=cp.float32)
    y = cp.empty_like(x)
    k = cp.RawKernel(KERNEL, "rmsnorm")
    for _ in range(ITERS):
        k((ROWS,), (THREADS,), (x, w, y, cp.int32(COLS // 4), cp.float32(EPS)))
    cp.cuda.Device().synchronize()
    out = os.environ.get("VTEC_OUT")
    if out:
        np.save(out, cp.asnumpy(y))
    print(f"rmsnorm {ROWS}x{COLS} x{ITERS}")

main()
